### ISSUE TITLE
Different translation - PHP Library vs Web Interface

### ISSUE THREAD

**Issue by alexgarciab** [statickidz/php-google-translate-free#13]
I have tried to implement the PHP Library and it works good, but I've realized that the translation generated with the PHP Library is different from the one generated with the Web Interface.

Is there a parameter that I need to change to get the latest results, the same ones that I am getting with the Web Interface?

**Comment by statickidz** [comment]
Actually, this library retrieves Google Translate app results, there is no way to switch that.
