### ISSUE TITLE
Translate not working

### ISSUE THREAD

**Issue by gsahu125** [statickidz/php-google-translate-free#17]
I am getting this error...
"""
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">\n
<TITLE>302 Moved</TITLE></HEAD><BODY>\n
<H1>302 Moved</H1>\n
The document has moved\n
<A HREF="https://www.google.com/sorry/index?continue=https://translate.google.com/translate_a/single%3Fclient%3Dat%26dt%3Dt%26dt%3Dld%26dt%3Dqca%26dt%3Drm%26dt%3Dbd%26dj%3D1%26hl%3Des-ES%26ie%3DUTF-8%26oe%3DUTF-8%26inputm%3D2%26otf%3D2%26iid%3D1dd3b944-fa62-4b55-b330-74909a99969e&amp;hl=es-ES&amp;q=EhAqAsIHIBhYBQAAAAAAAAABGJPPptkFIhkA8aeDSx1ib9AAOfrvNHAvkm6nTCEF4L4MMgFy">here</A>.\r\n ◀
</BODY></HTML>\r\n
"""

**Comment by statickidz** [comment]
According to the latest travis build:

https://travis-ci.org/statickidz/php-google-translate-free/builds/392343327

Seems like its working normally.

**Comment by MrFiregore** [comment]
Same issue ,What is the minimum time between querys to prevent block?
