### ISSUE TITLE
Didn't work

### ISSUE THREAD

**Issue by rasyid-irsyadi** [statickidz/php-google-translate-free#3]
didnt works for now

403
<ins>That’s an error.</ins><p>Your client does not have permission to get URL <code>/</code> from this server. (Client IP address: xxxx) 

 <ins>That’s all we know.</ins>

Please fix it, thanks :)

**Comment by statickidz** [comment]
Just looking for some time to implement [my php code](https://github.com/statickidz/php-google-translate-free) in js.

**Comment by rasyid-irsyadi** [comment]
Thanks :)
