### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fsn0w** [statickidz/php-google-translate-free#9]
hi,

Invalid argument supplied for foreach() in vendor/statickidz/php-google-translate-free/src/GoogleTranslate.php on line 123

**Comment by statickidz** [comment]
Can you please bring more info about how you're using it? Acording to the tests it seems it's working

**Comment by PFadlAssaad** [comment]
Well, I got the same error, and I noticed that this is happening when the text size is more than 5000 characters. 
Any idea?
